### ISSUE TITLE
Can't sync or migrate!

### ISSUE THREAD

**Issue by raonyguimaraes** [djaodjin/djaodjin-survey#1]
python manage.py syncdb
or
python manage.py migrate

raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, name))
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/raony/dev/torchsurveys/examples/djaodjin-survey/testsite/fixtures/initial_data.json': SurveyModel has no field named u'name'

**Comment by smirolo** [comment]
Thanks for the report!

I updated the fixtures because _name_ was renamed to _title_ in the SurveyModel.
